# WARNING: Encrypt this file with SOPS before committing.
# Run: sops --encrypt apps/immich/4-secrets.yaml > apps/immich/4-secrets.yaml
# (sops --in-place encrypts in-place)
#
# The age key for this repo is configured in .sops.yaml.
apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:ZnoRq93F5i03s7Da9MPXtYvjqd5Wr9NZCL/H/VOXcYVbT/Fos3qY5b7N/cgVXppfGn3NJAYIzoVJCow4Bigxxg==,iv:WhIEQpe3R2t1Zo0ODNMbuXT0B+tztbhP42TKzClaxwU=,tag:gpJrCK4nwx3Em1an9i64mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcFFuUHBtMVNqRTIxSkZx
            Ky9GajB0OWFCUGcweW1jNGtJNnlrRTdmRW1jCjFpQ1J1M2s2RjBEVVdCZkQxcVMr
            WjdNRExZRklPTml5bm9TQmhzUnM0QzQKLS0tIFNBMFZ3NEZQRno0OVdUV2U4dWY5
            Zkp2T05mNUh6aXhKY3RLRE52dTR5MmsKJ8i47QQau8GTu2o6kzOYwTLvH21qZnzC
            D2eEQdBZt8YdCZzFnedS0XJmsXQzAyCVSstw0lgWdfd1jQ8Y8SlyRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w67tp7vumngt0358xh63ayhlwkqc04tc7qk0nu6a7weg6arlqyxsrrexy6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T06:57:08Z"
    mac: ENC[AES256_GCM,data:BK1zSVAV7v+rjMT2EYlRQ4dsAbpLxFW4OpP5WtNmlfJs/T1du3xfXTV+eUN4+eFb56WbeAzTfvjt04pcLl6Cwx8KsMlhek998t0OqD2PRV4V6Q+m3/ovX+awYhv7nWZ4DBbjxttJWCnh7a9zREJITDHUBMOebOppsXNsvUgB4rg=,iv:NGQg1OGUEpKfQGpwZLj/eynv8VfxzEsXrjjCgirdY/c=,tag:yMtixocxuAyRYfgbZvbzlg==,type:str]
    version: 3.13.1
