apiVersion: v1
kind: Secret
metadata:
    name: juicefs-secret
    namespace: kube-system
    labels:
        juicefs.com/validate-secret: "true"
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:vPP982KffD9mng==,iv:BAl3kMeiw5SNqD9OfTk5FGrWYe4Umtm33GDxxPUTSb8=,tag:q7ymX93m0DYMXjtGzwc5dg==,type:str]
    metaurl: ENC[AES256_GCM,data:z0pdL1Y+zllksGz8bdznCuLbamFyRk5gQZtmGTNhScn/8tz4bQW7+rfRSZ+EPuJa8zgQ0hSwiO6Eo3gokA==,iv:QjqS7a4f6MBfZ+vguA87oQ0lMnNzTXMvytRpImIX7yA=,tag:WtvrHV2/+Im5nMgCn7+S5Q==,type:str]
    storage: ENC[AES256_GCM,data:QOA=,iv:YcWy0XqVr1z87+pJ7TWQvVQFdYaegfEVQmrBrxXq0vo=,tag:hc0g7hLGprfGSVkMLJB9Qw==,type:str]
    bucket: ENC[AES256_GCM,data:Bhbd9YidY/h44YnqHfiLS4rNB7SF5yFA40Mqmr0RAcHNTwH3fToh3nlVYeZvE8KR,iv:ZEuh4sk6Yyi9GSlZHIlnia55BjalzxjLlSZ5sqXtvAk=,tag:OFkMBB55J2yZRrOTgFhrnw==,type:str]
    access-key: ENC[AES256_GCM,data:kuuz5cTtOfLQTpSPBX421RH58gzzSTxbIQ==,iv:NvDOAKcieUVkOL2RxkRTca+Mk4CaMuEHFm+aYFUO4GM=,tag:KRdG/cTgc65sSAJxzix3kA==,type:str]
    secret-key: ENC[AES256_GCM,data:LS09Lw6/3dLNbvMm9q9FyKwPmjc0tO+IiwnMTI4fvg==,iv:3Xc1GzKEBcGHxNi/nKJNkXbz9zZogS5hiAoS56ojpxk=,tag:cqb5ux5Syb4hTshXpM4WQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcHdlUUQvVnFOcGRmODBx
            T1R4S2tybWJjK3NhakpoR1UvbnRGeXdtMDJNClVXcERFVHhjVjByTGc0Q044S3pR
            N2xaN0NSS0FjMktDYUExczZOYk9ZMW8KLS0tIER1WWdkaHNOa1RDcnd5MkxjNlpn
            RDNRQzlucWczV25ReUJIeENxMVR3N0UKAodwfpCAPRQG+DjOZICU2k/8qfpHxMpB
            BFJcOWxU27fAp0ggENhxXQgO9ULtLaPUEz16WshZARhTvlSvKvFwDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w67tp7vumngt0358xh63ayhlwkqc04tc7qk0nu6a7weg6arlqyxsrrexy6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T05:06:38Z"
    mac: ENC[AES256_GCM,data:9/IR0Q/dUxWH+gINz4H+1qU4sA61BAUgapLsxslMPAhN65T2SjSo25KO+5zZ7MGO9SMLulxI5f9hyS1yA6aYm+32PhaHgdBVGMJxebGxJUyRMSvERx9NRht9n3zUwynpWBjccHO9uxp/0E1T/r9tpkS/jI+LP8nzaWz0dUA53I8=,iv:k7LKwabU2WmXDdkP8jrmmkgC1dkEMmX4XrOZkIAVGho=,tag:4XOD0ysZKLuJQKww3vvNGQ==,type:str]
    version: 3.13.1
