apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-metadata-data
  namespace: kube-system
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
