apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: juicefs
  namespace: kube-system
spec:
  interval: 1h0m0s
  url: https://juicedata.github.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juicefs-csi-driver
  namespace: kube-system
spec:
  chart:
    spec:
      chart: juicefs-csi-driver
      sourceRef:
        kind: HelmRepository
        name: juicefs
      version: ">=0.32.0"
  interval: 1h0m0s
  targetNamespace: kube-system
  values:
    csidriver:
      disableHooks: true
