apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  labels:
    app: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: docker.io/louislam/uptime-kuma:2
          ports:
            - containerPort: 3001
              name: http
          volumeMounts:
            - name: data
              mountPath: /app/data
          env:
            - name: TZ
              value: America/Los_Angeles
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: uptime-kuma-data
