apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cliproxyapi-data
spec:
  storageClassName: maru-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
