apiVersion: v1
kind: Secret
metadata:
    name: cliproxyapi-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:JcdNLAKAcSQCH4Qzm+6dR/rwVSqzm+CAVPHaKVs4Gi52dRdntSdV2F1I/IoOPNXeevxTVGZ72+A7MdbESBBaP14JY7qmHflsVdGA7Jxr2Lglh8vqbWXxgYNZav5eMS1W45XKqjkuTGQaJXMIoJAIQcgFLdh5s05pJfa4HSh4nqVqcL9NTBgglhWRG05p+PJnHRbfsomTARcWhbRX9sM21CUypNcO/xbhXIT4gzgqwYZRqNupo36JfinZveXL72uBiQOlnHpPW0fLl5lpDQxmkmn/cWgeIq4ciRKeETFGhBpbsu57OHS/g1MIVt5h4Bg1jCuLTsn8NUMdhCaVbyp7QZnFzwFygysyrKfI4KiHbtI0aIR4AgifV/UJHhFVdvsE9JPuWSc3kpOyRZUYzUhkc5uUCl887upm2zGZetm6ojZDBThEevrSaUBYIj87jzJisfIbQpucBTjxlgLAFZShwM390g+bCdXSM0qcYYqc1SJMaue4ObTPmBZBpoGMHEZV44FfMcwILvE+eNdPk5f5AF9rdHv+Zf3MtxnoGh80dgMDvRaTjoG/kurfTjbhewfUDJS/3gaYCFxwUXS40b1l07OzaaECq3M7JiN+n21st9dX,iv:06Dyit49JuWwa3w8LSe1HGYVzX+HDJOMIL97HVew+cc=,tag:4BiBlTgn/CFQhu8OO3ziEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdzhkU1JSWFM1ZzlXQmFC
            N0ZYVkdTQmtWREhJajZzeFAzNlhscHZ0TUNNCi9lckRGUGpHVkFXclJQcjRubFRi
            V2V4WTIvVytUcE9FUnJLQy9aZTM4Sm8KLS0tIGZyMVRjTTJCUGIwSzZuM3pEb1V6
            QjhHd0FmZENkZWw1UUhRZ2cyL0gvNXMKRP8nCU9xf2qR8C5oN265pKTfR5lK6rIp
            UbNX88aw2JxJl1Hza4sxL9cpuvNmkZZFtZ1f887oMxspXJjSgb+Zqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w67tp7vumngt0358xh63ayhlwkqc04tc7qk0nu6a7weg6arlqyxsrrexy6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T05:27:07Z"
    mac: ENC[AES256_GCM,data:Auaa+BJKobpLoBnjBmQzk4bs8YPy5jDL4fR5mZ2Eitdg9zFmEVGR9igYidlixidxH+91hRvt+WO+nac+JRb2fWEtYKQ7VGSRltVr5vn30bwoGENu7ht8bhKRi5jh7BCMCFhdDbzdxI+ZAbaQQUpG2621yml2ShdaT5XOAnFqLyY=,iv:1okF8jb4CRDXIf68A4FVwvVMxg0h5bMOFQfbYUoXBf0=,tag:3govkgKVtF+U1Kr4AG7m5A==,type:str]
    version: 3.13.1
