apiVersion: v1
kind: Secret
metadata:
    name: cliproxyapi-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:IBZ5biYTPgKD24umjr5IvlkE+BhkPIPMcFmPdhgvckpmbAERlIasuAcKlPgdxV+5+5AX4fcUpKTrvzn4OoJcJtVWiiRaL5SlqJjQ+T0sZZsy27yfVSy56Jp9T0Cd2IGPdOXstAVGkgh2dRxWpEJuCAK5irw3aoW4H+YHQJy7hWYCEtoFxpE0WVewJgklTHUxIW/Ib8T+koJUbkS4s+dl5dqakAmyPAiXEHsFFxQK5ZqIw86XyFfvuYEV4bEtmu4sIlVdrsHFHDX/CUqLw54Cs22fJboMmKGYIWmu2nLCk+9bC5ckUzl4iRI5ipl0emQUSf0SIOz2pdr6khLOfnNY+t3zt3rerduSemYUY1ew5dOaTxwDw4ts+qoUCeFeIpYg9Akk5NcBCamJ8v92sRA9/vlXwHTJaB+fzLYhVxNiNXwXsRvxwJxjIv1voQ7eK8n4jz7w9opMdy+ptlVRU2zTKc4I/POvJegxdiRcmAwWI7WQaAkL2/boX8oDMU3d5PxgzKK9u5A6OEIMYzHSBsdXr6kgMPrY8D6XgIbic1BRbq39PV2kAYYphrXO4EZavkKXmnl5pvyN7g1xMjKQG2+JAzw93CjBCyUdq2CRDXjQz0K/ryhfPenjDtXzbYv1BG2JuvjMx2BRhS2FEAzRhlDjETEJKdSSWoTaELkqzRkffILH+kp4cZFOPHgtyiTAuX+BdraqvbLxoRiJG7cWVBAvwrSTvWvhUZBH7Ta1y9MlEqj8zCzoI9aKBlC5W/JEnvEruWGpJPgZYT2j6euxMcVYbSo3C26PS8MnqZpb/BowGnVFhob2biFrYAJfzaGGgi36BIp31OekcHw0ILJP32JLtc96Z/4q0pYNHae2CTZdr03qm6tKzwJcv/R8nMkdafoSscmteWFRE8o3HgtT/agImZRle5uSE/cypQe9Ua1Q0QUFJLloBhlN7SNhxKuoYxipni3IF4UKqO65VHjDfS+n8EggorpAdIOWm3W2OBzqWyFeg/S2d4+GESVFJ3KqOLadcBRxpH2k9+dhM4N2hiJg+8zVmYtRxyvz8PBTcFNlQ+mNsd200/L1A/WH/arCKG3dyfKO36iy2sp4,iv:qDbVMwb4WNqMfJ4gWxwqBcDmgYKzS12tXdFVWm4eq54=,tag:B/Ub73Iqb6DKHlkFsVmkBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcnpmdE1rQXdBS0M5aUJW
            dGJXUVpkU3NjZUM4S080ME9Ic3dvS1VFVGx3Cm9JS1JKUHBlVmVnbGFqR3R3YUFJ
            eHdWc2dsOUZTNENsQ2NuUFdjVWZsVlkKLS0tIHhzN3FwQlo5SWZ1U0xnWWJObHE1
            NzJzVzJtamJWcU8zTUhSYmQyNlQ0REUKu9gnnfGcvm1newxHa5ZCYf9rCU5ReEqN
            G82MA8voSTIOcl835lu4VCmbGIEAZ7UV9sF+0/A++Jp9N0RGPVUn1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w67tp7vumngt0358xh63ayhlwkqc04tc7qk0nu6a7weg6arlqyxsrrexy6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T04:14:58Z"
    mac: ENC[AES256_GCM,data:uKNN6FivHvYudO1QplQnzvCJYKSWU7M+abk0XQ+clSUooVXN5nMr1sNHmTQQBsx2RSqJwoi49lk9pzvI5WtUWi73R7840xD3rFivQ1v1EPr7XB8/jcGmzWd7ooxbDZLNqxSYuH9p/+RhcqTImTLwyym+hB0seMk3eO4edNO0mCA=,iv:uP/aPi4JMZzwUtra+NeOSe44hsiAnz3AYz0gUwk+sp4=,tag:QibljV0Gcj2QWKu31ss2jQ==,type:str]
    version: 3.13.3
