apiVersion: v1
kind: Secret
metadata:
    name: cliproxyapi-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:Sxi0d+dgwIieFm1Th1w1R1YsGUF300srDcSrSFU/HGIefj/e7F38NfBQ16Mk+c1tlIrP8r2hlJNlXps2dQXh0p7PG8cIIVd9yVbK7zMUqYJ0PFmMufo0iUn1sJhd2VOOrcoG5QjFJH4gq3TQ6nEcUJLTMGidUEgsAliqlgtum3SXKzUr0jXMwDhzG3BnfChfcWsYuAfRT1Eg2c7lbLEkTmPgbu/PUT/ITD/XXqxCB7RZrc2b2OT9NEeAF/vToTPbOXcFCC4GhsfyCvWvhrdWWn9cnw8LuVD6ZeCy7df+QwXgjFb4g3esN0JV7xKxwpk4bvbQQ/6re39xv7yM6xwSS2aJg+klyNUxLRYWw2LQ18bD2Bz++jIjs5WqwAopbOr+/E282ExriPzSMEVnN69kjT0jPYPPwSv159veTMmvv3caAPsMsRlIe+H7jCGaN6My1d6jYb8wgqeAp+X+LF9U1TJqo+FAFEHc8hp3kJA+AFVpkbPMjtu4ikvzfUbRnHO/LHIdEifWugp0IdHqTfTqHklq0U7OEnCZVd3kh2gjxufCzufSFu909xy9Gr84OlxHtlwjk0x8rnI3Ynqj1jCciwKA2hAi9WAhjCBQdL4hy3O6x5ttAYnCz7FHSRLOJhWpZAtsl88Be8hXyuTN+FCF96JOpATLMxOB+nci/Gm3X+V4Z6IPp+dhXLwDsAXvFi+VLA7NxSp+0hDVBnkQf/SbdrwR34152rhjGdh73s4V91knJQCaGqptUCxHPeQHX8CJpD07Bdnh70WCmKLehA8iob+KeLjgYHc9MnR0phbc+CSOe7swP9SHEvUrAR+YaI9mv8SOiestiBkt3M/ysTHUfl0tyyPm//i1kYOnVQq4l4mq0eAas4YKvYfQqQwrtQtdN6fkSw5HAK8jFkcAQ1W8XXL39TKxe42R/OyDB77MtiEz+sXfQDW3pXMwBa3nMtXWI+7IQ74vMSKlEeTxoede8TneZi04FWfivbIOclzbyGxe9HK0blBRRwHmcLy1k7HmUpY4B8Hpm1Mny7bJ1T+SSjR0Td9Ke2gVkVpkWdEWt0fwCTmKmGmzNyo78x0agvpIHRFCeevJd28KU3U1IZXyyXc=,iv:zFRcaGyD4ijkIRN+Si24DdA6Md78crDaqo+XcgwnkPU=,tag:/1rWmB/WHTGUpPxinffQBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbUlPM3Jhd3NidVg0OWM2
            NVdqblU5UkR0Nzg4bUFsM2dDLzFlMGFGQXlJCnY3MmpOZnRlSXAzY3RUVUc3bDBL
            WTBZOWFiUGcrYXBNL1pSRm1kUTFjOWcKLS0tIE5OSzNvQ3FMMGN0aWl5NGJRNmtn
            aFErMS9vdVhpZ3FMUEtGMEd0Qk0yWGsKLxPocMy2k/qONnLOQTVg9x6XuAcsPKJW
            OwZNk+HbEyCp2AGLwUz1xQif6+s2JbfiLL83WvCk4mTcO27rlRkmtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w67tp7vumngt0358xh63ayhlwkqc04tc7qk0nu6a7weg6arlqyxsrrexy6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T23:58:00Z"
    mac: ENC[AES256_GCM,data:TZtV/Na8yVh/Ee/SiwND4iBt0RKdkbhciy/Mgnh4jkNf7xUfQQTa3MIlx/o4ysDjlHm5SVMxvUef+Pp8yO8Sr+mOF5eQswYrIY59jKKYVXAVOjaQ2caMDdJ1GRS6tNIf6joPk4lS8gCISUxj17YngxcTerut7fnj+UBqckqoWtU=,iv:BvMTjQ1YrcfyPDBENgrU3Q1vCqDStNAVVjlelMGAyiw=,tag:Zo0JQnxkHbuuCamNads08w==,type:str]
    version: 3.13.3
