apiVersion: v1
kind: Service
metadata:
  name: cliproxyapi
  labels:
    app: cliproxyapi
spec:
  type: ClusterIP
  ports:
    - port: 8317
      targetPort: 8317
      name: http
  selector:
    app: cliproxyapi
