apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 1h0m0s
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
      version: '>1.92.0'
  targetNamespace: tailscale
  interval: 1m0s
  valuesFrom:
    - kind: Secret
      name: tailscale-secret-values
  values:
    operatorConfig:
      hostname: "kinako"
    apiServerProxyConfig:
      mode: "true"
