apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencode-workspace
spec:
  storageClassName: maru-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
