apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mc-1122
  name: mc-1122
spec:
  type: LoadBalancer
  ports:
  - name: "25566"
    port: 25566
    targetPort: 25565
  selector:
    io.kompose.service: mc-1122
