apiVersion: v1
kind: Service
metadata:
  annotations:
    "mc-router.itzg.me/externalServerName": "vanilla.mc.treelar.xyz"
    "mc-router.itzg.me/autoScaleUp": "true"
    "mc-router.itzg.me/autoScaleDown": "true"
  name: vanilla-minecraft
spec:
  ports:
    - port: 25565
  selector:
    app: vanilla-minecraft
